### ISSUE TITLE
The "src" folder is confusing most users

### ISSUE THREAD

**Issue by XenonA7** [CCDirectLink/char-select#1]
Most users put this mod into their **assets\mods** and it doesn't work due to the src folder. Please consider adding special install instructions or putting the mod files in the root.

![image](https://github.com/CCDirectLink/char-select/assets/105614278/0253d9fa-863d-4a49-8315-f0112ea97de6)

![image](https://github.com/CCDirectLink/char-select/assets/105614278/8b234fbb-7c2d-4d4e-a00b-9c1897235327)

![image](https://github.com/CCDirectLink/char-select/assets/105614278/468f89a3-7aaa-481a-b271-0c1c71f7f7f1)

![image](https://github.com/CCDirectLink/char-select/assets/105614278/1ac11d1e-1e8c-46de-a30b-e6a17d7814c3)

**Comment by 2767mr** [comment]
Fixed in #2
